#include<stdio.h>
#include<string.h>
#include<assert.h>
#define $$$

$$$

char yytext[1000000];
int yyleng;
void* yylex();
/******************************************************
 * user defined functions in lex
 ******************************************************/

$$$

/******************************************************
 * user defined actions in lex
 ******************************************************/

$$$

/****************************************************
 * dfa things
 ****************************************************/
int n,start,cur;
int to[5000][256];
int accept[5000];
void* (*action_of_node[5000])();

void dfa_init(){
    memset(to,-1,sizeof to);
    memset(accept,0,sizeof accept);
}

void dfa_set_edge(int i,int j,int x){
    to[i][x]=j;
}

void dfa_set_action(int node_id,void* (*action)()){
    accept[node_id]=1;
    action_of_node[node_id]=action;
}

void dfa_build(){
    dfa_init();
    /******************************************
     * codes below are generated by lex
     ******************************************/
    // n=...
    // start=...
    // dfa_set_edge...
    // dfa_set_rule...
$$$
}

int dfa_step(char ter){
    if(to[cur][ter]==-1)
        return 1;
    cur=to[cur][ter];
    return 0;
}

int dfa_acceptable(int i){
    return accept[i]==1;
}

void* do_action(int i){
    assert(dfa_acceptable(i));
    return action_of_node[i]();
}

/*******************************************************
 * yy things
 *******************************************************/

FILE *fp;

void* yylex(){
    int last_ac=-1,last_ac_len=0;
    yyleng=0;
    cur=start;
    while(!feof(fp)){
        char x=fgetc(fp);
        yytext[yyleng++]=x;
        yytext[yyleng]=0;
        if(dfa_step(x)!=0){
            while(yyleng>last_ac_len)
                ungetc(yytext[--yyleng],fp);
            yytext[yyleng]=0;
            break;
        }
        if(dfa_acceptable(cur)){
            last_ac=cur;
            last_ac_len=yyleng;
        }
    }
    if(yyleng==0){
        if(feof(fp)){
            printf("work is done\n");
        }else{
            perror("error when tokenizing\n");
        }
        fclose(fp);
        exit(0);
    };
    return do_action(cur);
}

int main(int argc,char **argv){
    assert(argc>=2);
    fp=fopen(argv[1],"r");
    if(fp==NULL){
        printf("open file error!\n");
        return 0;
    }
    dfa_build();
    while(1)yylex();
}